### ISSUE TITLE
"stack setup" fails

### ISSUE THREAD

**Issue by rafoo** [tip-org/tools#22]
Hello,

I would like to try TIP but I cannot install the tools. I get the following error when running the first command of the installation process `stack setup`:

```
Could not parse 'stack.yaml':
AesonException "Error in $['extra-deps'][10]: failed to parse field 'extra-deps': failed to parse field extra-deps: expected PackageIdentifier, encountered Object"
See http://docs.haskellstack.org/en/stable/yaml_configuration/.
```

The error seems located at line 21 of `stack.yaml`: 
```
- git: git://github.com/nick8325/quickspec
  commit: 0d0b72e30bb2ec30e95be53839f671f3682bb6a1
```

I am running Debian Stable (Stretch), and stack reports the following version string: `Version 1.1.2 x86_64 hpack-0.14.1`.

**Comment by solrun** [comment]
Hi @rafoo, 
This is due to the new syntax for listing a git repo as a dependency in a stack configuration file, which is supported in stack versions 1.5.1 and newer (see https://www.fpcomplete.com/blog/2017/07/stacks-new-extensible-snapshots).
This issue should be solved if you upgrade your stack version (i.e. by running ```stack upgrade```), or, if you want to keep using the older stack version, you can edit your ```stack.yaml``` file, deleting lines 21-22 and inserting the quickspec git-repo in the packages list, as we did previously, see https://github.com/tip-org/tools/blob/13577957bdf3ce2948693805c097e5a8501fd2b4/stack.yaml (but make sure to use the more recent commit hash that's specified in the current stack.yaml).

Hope this helps and you manage to install the tools!

**Comment by solrun** [comment]
@nick8325: We could avoid issues like this by configuring ```require-stack-version``` in ```stack.yaml```, or use the old syntax with an ```extra-dep:true``` field, which seems to be compatible with newer and older versions of stack.

**Comment by rafoo** [comment]
Thank you for the quick reply, the Debian version of stack seems too old for being upgradable but installing a recent stack following the instructions at https://docs.haskellstack.org/en/stable/install_and_upgrade/#linux solved the issue.

**Comment by solrun** [comment]
I've now changed the syntax in ```stack.yaml``` so it should be compatible with older and newer stack versions (https://github.com/tip-org/tools/commit/9fea7662a60caded8e07e9c1b7b2de64f5673e0d).
