### ISSUE TITLE
RemoveNewType removes needed data types

### ISSUE THREAD

**Issue by chip2n** [tip-org/tools#4]
The RemoveNewType pass removes needed data types in the generated TIP code. This seems to happen when data type has at least one type variable and a single type constructor.

Example:

```
data Foo a = Bar a

prop :: Foo a -> Equality Bool
prop _ = bool True
```

causes the following error:

```
tip-ghc: Lint failed after RemoveNewtype(after SimplifyGently):
Type constructor Foo not in scope
in context
  (assert-not (par (a) (forall ((x (Foo a))) true)))
in context
  (assert-not (par (a) (forall ((x (Foo a))) true)))
  (check-sat)
!!!
```

Same thing happens if Foo is a newtype.

**Comment by danr** [comment]
Thanks,

Do you want to have a go at fixing it?

The simple fix is to make sure that there are no type variables here:
https://github.com/tip-org/tools/blob/master/tip-lib/src/Tip/Pass/RemoveNewtype.hs#L51

The interesting fix is to save the name of the type variables, not only the
type, and do a type substitution here:
https://github.com/tip-org/tools/blob/master/tip-lib/src/Tip/Pass/RemoveNewtype.hs#L27
(the pattern two lines above says that the type constructor tc is applied
to new arguments: this is where the actual bug is!!)

/Dan

**Comment by chip2n** [comment]
Sure, I'll take a look at it later this week.
