### ISSUE TITLE
AxiomatizeFuncdefs removes declarations of polymorphic functions

### ISSUE THREAD

**Issue by aztek** [tip-org/tools#8]
```
$ cat test.smt2
(declare-datatypes (a)
  ((list (nil) (cons (head a) (tail (list a))))))
(define-fun
  (par (a)
    (isnil ((xs (list a))) Bool
      (match xs
        (case nil true)
        (case (cons x xs) false)))))
(assert-not
  (isnil (as nil (list Bool))))
(check-sat)

$ tip test.smt2 --smtlib --axiomatize-funcdefs
(declare-sort sk 0)
(declare-datatypes ()
  ((list (nil) (cons (head Bool) (tail list)))))
(declare-fun isnil (list) Bool)
(assert (not (isnil nil)))
(check-sat)
```

**Comment by danr** [comment]
The axiomatize funcdefs pass is run before --smtlib, which probably makes
the monomorphiser remove it:

https://github.com/tip-org/tools/blob/master/tip-lib/executable/Main.hs#L82

Try using the --smtlib-ax-fun flag instead.

/Dan

**Comment by aztek** [comment]
> Try using the --smtlib-ax-fun flag instead.

Do you mean instead of `--smtlib` or instead of both `--smtlib --axiomatize-funcdefs`? In the first case there is no difference, in the second case it seems to help

```
$ tip test.smt2 --smtlib-ax-fun
(declare-sort sk 0)
(declare-datatypes ()
  ((list (nil) (cons (head Bool) (tail list)))))
(declare-fun isnil (list) Bool)
(assert (not true))
(assert (forall ((xs list)) (= (isnil xs) (not (is-cons xs)))))
(check-sat)
```

However it did not generate a definition for `is-cons`. There is no convention in SMT-LIB that every datatype declaration implicitly comes with definitions of discriminators, is there?

What I am trying to do here is convert TIP benchmarks to something that Vampire can read. Monomorphic axioms for recursive functions and monomorphic datatype declarations would be ideal.

**Comment by nick8325** [comment]
> However it did not generate a definition for `is-cons`. There is no convention in SMT-LIB that every datatype declaration implicitly comes with definitions of discriminators, is there?

Both Z3 and CVC4 automatically define discriminators with `is-` names when you declare a datatype (I do think it's a bit weird, though).

If you use `--axiomatize-funcdefs2` you get a translation which avoids using the discriminators by eliminating `match` altogether:

```
(declare-datatypes (a)
  ((list (nil) (cons (head a) (tail (list a))))))
(declare-fun (par (a) (isnil ((list a)) Bool)))
(assert (par (a) (= (isnil (as nil (list a))) true)))
(assert
  (par (a)
    (forall ((x a) (xs (list a))) (= (isnil (cons x xs)) false))))
(assert-not (isnil (as nil (list Bool))))
(check-sat)
```

To combine this with the monomorphiser you need to run the following command:

```
tip test.smt2 --type-skolem-conjecture --monomorphise --axiomatize-funcdefs2 --smtlib
```

This makes sure that the problem is monomorphised _before_ axiomatising the function definitions. Otherwise the monomorphiser deletes too much stuff at the moment because it's buggy. This trick seems to work with `--axiomatize-funcdefs` as well.

**Comment by aztek** [comment]
> Both Z3 and CVC4 automatically define discriminators with is- names when you declare a datatype (I do think it's a bit weird, though).

Interesting! Maybe Vampire should do the same to comply.

> This makes sure that the problem is monomorphised before axiomatising the function definitions.

Is it because the order of options matters? I was using exactly these options, but in a different order, to translate all TIP problems.

This command does help in this case, but not generally. For example, `tip` still removes function definitions in `tip2015/list_return_2.smt2`. I can give you a larger list of files with this problem if that would help.

Are you planning to improve the monomorphiser any time soon? It would be very helpful for our work on inductive reasoning in Vampire.

**Comment by danr** [comment]
Note that SMTLIB 2.6 draft suggests an other syntax for the is-
discriminators, namely `(_ is cons)`. See page 59 and onwards in
http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-draft-3.pdf

> It also uses other syntax for datatype declarations and case expressions.

**Comment by danr** [comment]
I am not working on the monomorphiser.

**Comment by nick8325** [comment]
> Is it because the order of options matters? I was using exactly these options, but in a different order, to translate all TIP problems.

Yes, the passes are run in the order you specify. The monomorphiser needs to have function definitions rather than axioms at the moment, so it should be run before `--axiomatize-funcdefs`.

By the way, `--smtlib-ax-fun` is just an alias for a series of passes, currently the following:

```
--type-skolem-conjecture --monomorphise --lambda-lift --axiomatize-lambdas --simplify-gently --collapse-equal --remove-aliases --simplify-gently --remove-match --simplify-gently --monomorphise --axiomatize-funcdefs --simplify-gently --negate-conjecture
```

So replacing `--axiomatize-funcdefs` with `--axiomatize-funcdefs2` in the above should work. If you still have trouble with the monomorphiser, you could try the following variant, which only runs the monomorphiser once:

```
--lambda-lift --axiomatize-lambdas --simplify-gently --remove-match --type-skolem-conjecture --monomorphise --axiomatize-funcdefs --negate-conjecture --simplify-gently
```

> This command does help in this case, but not generally. For example, tip still removes function definitions in `tip2015/list_return_2.smt2`. I can give you a larger list of files with this problem if that would help.

Argh, that is very annoying! After you monomorphise the problem, `--smtlib` runs the monomorphiser itself - at this point the problem is monomorphic but the monomorphiser throws stuff away anyway!

> Are you planning to improve the monomorphiser any time soon? It would be very helpful for our work on inductive reasoning in Vampire.

I will at least try to poke around in it and find the bugs.
